title: Stewart Calculus Playlists
description: Organized playlists for selected sections.
theme: jekyll-theme-hacker
markdown: kramdown
kramdown:
  input: GFM       # Enables GitHub Flavored Markdown
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..6
